ci(workflow): format YAML indentation and improve toolchain setup steps

diff --git a/.github/workflows/build_kernel_gki.yml b/.github/workflows/build_kernel_gki.yml
--- a/.github/workflows/build_kernel_gki.yml
+++ b/.github/workflows/build_kernel_gki.yml
@@ -55,8 +55,8 @@ jobs:
     permissions: write-all
     defaults:
       run:
-       shell: bash
-       working-directory: ${{ github.workspace }}
+        shell: bash
+        working-directory: ${{ github.workspace }}
 
     steps:
       - name: Set-up environment
@@ -86,14 +86,14 @@ jobs:
           
       - name: Set-up Toolchain
         run: |
-         mkdir -p ${{ github.workspace }}/toolchain
-         if [[ "${{ github.event.inputs.TOOLCHAIN_URL }}" == *.tar.gz ]]; then
-             wget -O clang-toolchain.tar.gz "${{ github.event.inputs.TOOLCHAIN_URL }}"
-             tar -xzf clang-toolchain.tar.gz -C ${{ github.workspace }}/toolchain
-             rm -f clang-toolchain.tar.gz
-         else
-             git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.TOOLCHAIN_URL }} ${{ github.workspace }}/toolchain
-         fi
+          mkdir -p ${{ github.workspace }}/toolchain
+          if [[ "${{ github.event.inputs.TOOLCHAIN_URL }}" == *.tar.gz ]]; then
+              wget -O clang-toolchain.tar.gz "${{ github.event.inputs.TOOLCHAIN_URL }}"
+              tar -xzf clang-toolchain.tar.gz -C ${{ github.workspace }}/toolchain
+              rm -f clang-toolchain.tar.gz
+          else
+              git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.TOOLCHAIN_URL }} ${{ github.workspace }}/toolchain
+          fi
 
       - name: Set environment variables
         run: |
@@ -112,131 +112,130 @@ jobs:
           echo "KERNEL_SOURCE_URL=${KERNEL_SOURCE_URL}" >> $GITHUB_ENV
 
       - name: Start Compilation
-        run: |
-         set -e # Exit immediately if a command exits with a non-zero status
-         mkdir -p ${{ env.OUTPUT_DIR }}
-         cd ${{ github.workspace }}/kernel
-         
-         export PATH="${{ env.CLANG_DIR }}/bin:$PATH"
-         start=$(date +"%s")
-         
-         echo "=============================================="
-         echo "1. Generating Defconfig"
-         echo "=============================================="
-         make -s ARCH=arm64 O=${{ env.OBJDIR }} ${{ github.event.inputs.CONFIG_FILE }} -j$(nproc --all)
-         
-         echo "=============================================="
-         echo "2. Building Main Kernel & Internal Modules"
-         echo "=============================================="
-         make -j$(nproc --all) \
-         O=${{ env.OBJDIR }} \
-         ARCH=arm64 \
-         CC=clang \
-         KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" \
-         CROSS_COMPILE=aarch64-linux-gnu- \
-         CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-         CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
-         AR=llvm-ar \
-         LLVM_NM=llvm-nm \
-         OBJCOPY=llvm-objcopy \
-         LD=ld.lld \
-         NM=llvm-nm \
-         LLVM=1 \
-         LLVM_IAS=1 \
-         dtbs modules Image.gz
-
-         echo "=============================================="
-         echo "3. Building Out-of-Tree Modules (sm6475-modules)"
-         echo "=============================================="
-         MODULES_DIR="${{ github.workspace }}/sm6475-modules"
-         
-         # Build NXP NFC Driver
-         if [ -d "${MODULES_DIR}/nxp/opensource/driver" ]; then
-             echo "--> Building NXP Modules..."
-             make -j$(nproc --all) O=${{ env.OBJDIR }} ARCH=arm64 CC=clang KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- AR=llvm-ar LLVM_NM=llvm-nm OBJCOPY=llvm-objcopy LD=ld.lld NM=llvm-nm LLVM=1 LLVM_IAS=1 M=${MODULES_DIR}/nxp/opensource/driver modules
-         else
-             echo "--> WARNING: NXP directory not found!"
-         fi
-
-         # Build QCOM Drivers
-         if [ -d "${MODULES_DIR}/qcom/opensource" ]; then
-             for mod in ${MODULES_DIR}/qcom/opensource/*; do
-                 # Verify directory contains Kbuild or Makefile to avoid build errors
-                 if [ -d "$mod" ] && { [ -f "$mod/Kbuild" ] || [ -f "$mod/Makefile" ]; }; then
-                     echo "--> Building QCOM module: $(basename $mod)"
-                     make -j$(nproc --all) O=${{ env.OBJDIR }} ARCH=arm64 CC=clang KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- AR=llvm-ar LLVM_NM=llvm-nm OBJCOPY=llvm-objcopy LD=ld.lld NM=llvm-nm LLVM=1 LLVM_IAS=1 M=$mod modules
-                 fi
-             done
-         else
-             echo "--> WARNING: QCOM directory not found!"
-         fi
-
-         end=$(date +"%s")
-         diff=$((end - start))
-         echo -e "BUILD COMPLETED IN ${diff} SECONDS"
-
         continue-on-error: false
+        run: |
+          set -e # Exit immediately if a command exits with a non-zero status
+          mkdir -p ${{ env.OUTPUT_DIR }}
+          cd ${{ github.workspace }}/kernel
+          
+          export PATH="${{ env.CLANG_DIR }}/bin:$PATH"
+          start=$(date +"%s")
+          
+          echo "=============================================="
+          echo "1. Generating Defconfig"
+          echo "=============================================="
+          make -s ARCH=arm64 O=${{ env.OBJDIR }} ${{ github.event.inputs.CONFIG_FILE }} -j$(nproc --all)
+          
+          echo "=============================================="
+          echo "2. Building Main Kernel & Internal Modules"
+          echo "=============================================="
+          make -j$(nproc --all) \
+          O=${{ env.OBJDIR }} \
+          ARCH=arm64 \
+          CC=clang \
+          KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" \
+          CROSS_COMPILE=aarch64-linux-gnu- \
+          CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
+          CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
+          AR=llvm-ar \
+          LLVM_NM=llvm-nm \
+          OBJCOPY=llvm-objcopy \
+          LD=ld.lld \
+          NM=llvm-nm \
+          LLVM=1 \
+          LLVM_IAS=1 \
+          dtbs modules Image.gz
+
+          echo "=============================================="
+          echo "3. Building Out-of-Tree Modules (sm6475-modules)"
+          echo "=============================================="
+          MODULES_DIR="${{ github.workspace }}/sm6475-modules"
+          
+          # Build NXP NFC Driver
+          if [ -d "${MODULES_DIR}/nxp/opensource/driver" ]; then
+              echo "--> Building NXP Modules..."
+              make -j$(nproc --all) O=${{ env.OBJDIR }} ARCH=arm64 CC=clang KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- AR=llvm-ar LLVM_NM=llvm-nm OBJCOPY=llvm-objcopy LD=ld.lld NM=llvm-nm LLVM=1 LLVM_IAS=1 M=${MODULES_DIR}/nxp/opensource/driver modules
+          else
+              echo "--> WARNING: NXP directory not found!"
+          fi
+
+          # Build QCOM Drivers
+          if [ -d "${MODULES_DIR}/qcom/opensource" ]; then
+              for mod in ${MODULES_DIR}/qcom/opensource/*; do
+                  # Verify directory contains Kbuild or Makefile to avoid build errors
+                  if [ -d "$mod" ] && { [ -f "$mod/Kbuild" ] || [ -f "$mod/Makefile" ]; }; then
+                      echo "--> Building QCOM module: $(basename $mod)"
+                      make -j$(nproc --all) O=${{ env.OBJDIR }} ARCH=arm64 CC=clang KCFLAGS="-Wno-frame-larger-than -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types" CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- AR=llvm-ar LLVM_NM=llvm-nm OBJCOPY=llvm-objcopy LD=ld.lld NM=llvm-nm LLVM=1 LLVM_IAS=1 M=$mod modules
+                  fi
+              done
+          else
+              echo "--> WARNING: QCOM directory not found!"
+          fi
+
+          end=$(date +"%s")
+          diff=$((end - start))
+          echo -e "BUILD COMPLETED IN ${diff} SECONDS"
 
       - name: Checking for outputs and Packing AnyKernel
         run: |
-         cd "${{ env.OBJDIR }}"
-         
-         # Print contents of the boot directory to verify files exist
-         echo "Checking contents of arch/arm64/boot/ :"
-         ls -la arch/arm64/boot/ || echo "boot directory not found!"
-         
-         compiled_image="arch/arm64/boot/Image"
-         compiled_gz_image="arch/arm64/boot/Image.gz"
-         compiled_gz_dtb="arch/arm64/boot/Image.gz-dtb"
-         compiled_dtbo="arch/arm64/boot/dtbo.img"
-         compiled_dtb_img="arch/arm64/boot/dtb.img"
-         compiled_dtb="arch/arm64/boot/dtb"
-           
-         if [[ -f "${compiled_image}" || -f "${compiled_gz_image}" || -f "${compiled_gz_dtb}" ]]; then
-              echo "Kernel output found! Preparing AnyKernel..."
-              git clone -q ${{ github.event.inputs.ANYKERNEL }} "${{ env.ANYKERNEL }}"
+          cd "${{ env.OBJDIR }}"
+          
+          # Print contents of the boot directory to verify files exist
+          echo "Checking contents of arch/arm64/boot/ :"
+          ls -la arch/arm64/boot/ || echo "boot directory not found!"
+          
+          compiled_image="arch/arm64/boot/Image"
+          compiled_gz_image="arch/arm64/boot/Image.gz"
+          compiled_gz_dtb="arch/arm64/boot/Image.gz-dtb"
+          compiled_dtbo="arch/arm64/boot/dtbo.img"
+          compiled_dtb_img="arch/arm64/boot/dtb.img"
+          compiled_dtb="arch/arm64/boot/dtb"
+            
+          if [[ -f "${compiled_image}" || -f "${compiled_gz_image}" || -f "${compiled_gz_dtb}" ]]; then
+               echo "Kernel output found! Preparing AnyKernel..."
+               git clone -q ${{ github.event.inputs.ANYKERNEL }} "${{ env.ANYKERNEL }}"
 
-              if [[ -f "${compiled_image}" ]]; then
-                  cp -f "${compiled_image}" "${{ env.ANYKERNEL }}/Image" || true
-              elif [[ -f "${compiled_gz_image}" ]]; then
-                  cp -f "${compiled_gz_image}" "${{ env.ANYKERNEL }}/Image.gz" || true
-              elif [[ -f "${compiled_gz_dtb}" ]]; then
-                  cp -f "${compiled_gz_dtb}" "${{ env.ANYKERNEL }}/Image.gz-dtb" || true
-              fi
-              
-              # Copy DTBO & DTB
-              find arch/arm64/boot/dts/ -name "*.dtbo" -exec cp -f {} "${{ env.ANYKERNEL }}/" \; 2>/dev/null || true
-              find arch/arm64/boot/dts/ -name "*.dtb" -exec cp -f {} "${{ env.ANYKERNEL }}/" \; 2>/dev/null || true
+               if [[ -f "${compiled_image}" ]]; then
+                   cp -f "${compiled_image}" "${{ env.ANYKERNEL }}/Image" || true
+               elif [[ -f "${compiled_gz_image}" ]]; then
+                   cp -f "${compiled_gz_image}" "${{ env.ANYKERNEL }}/Image.gz" || true
+               elif [[ -f "${compiled_gz_dtb}" ]]; then
+                   cp -f "${compiled_gz_dtb}" "${{ env.ANYKERNEL }}/Image.gz-dtb" || true
+               fi
+               
+               # Copy DTBO & DTB
+               find arch/arm64/boot/dts/ -name "*.dtbo" -exec cp -f {} "${{ env.ANYKERNEL }}/" \; 2>/dev/null || true
+               find arch/arm64/boot/dts/ -name "*.dtb" -exec cp -f {} "${{ env.ANYKERNEL }}/" \; 2>/dev/null || true
 
-              if [[ -f "${compiled_dtbo}" ]]; then
-                  cp -f "${compiled_dtbo}" "${{ env.ANYKERNEL }}/dtbo.img" || true
-              fi
- 
-              if [[ -f "${compiled_dtb_img}" ]]; then
-                  cp -f "${compiled_dtb_img}" "${{ env.ANYKERNEL }}/dtb.img" || true
-              elif [[ -f "${compiled_dtb}" ]]; then
-                  cp -f "${compiled_dtb}" "${{ env.ANYKERNEL }}/dtb" || true
-              fi
+               if [[ -f "${compiled_dtbo}" ]]; then
+                   cp -f "${compiled_dtbo}" "${{ env.ANYKERNEL }}/dtbo.img" || true
+               fi
+  
+               if [[ -f "${compiled_dtb_img}" ]]; then
+                   cp -f "${compiled_dtb_img}" "${{ env.ANYKERNEL }}/dtb.img" || true
+               elif [[ -f "${compiled_dtb}" ]]; then
+                   cp -f "${compiled_dtb}" "${{ env.ANYKERNEL }}/dtb" || true
+               fi
 
-              # Collect all compiled modules (.ko) from both the build path and external modules directory
-              echo "Gathering compiled .ko modules..."
-              mkdir -p "${{ env.ANYKERNEL }}/modules/system/lib/modules"
-              find ${{ env.OBJDIR }} -name "*.ko" -exec cp -f {} "${{ env.ANYKERNEL }}/modules/system/lib/modules/" \; 2>/dev/null || true
-              find ${{ github.workspace }}/sm6475-modules -name "*.ko" -exec cp -f {} "${{ env.ANYKERNEL }}/modules/system/lib/modules/" \; 2>/dev/null || true
+               # Collect all compiled modules (.ko) from both the build path and external modules directory
+               echo "Gathering compiled .ko modules..."
+               mkdir -p "${{ env.ANYKERNEL }}/modules/system/lib/modules"
+               find ${{ env.OBJDIR }} -name "*.ko" -exec cp -f {} "${{ env.ANYKERNEL }}/modules/system/lib/modules/" \; 2>/dev/null || true
+               find ${{ github.workspace }}/sm6475-modules -name "*.ko" -exec cp -f {} "${{ env.ANYKERNEL }}/modules/system/lib/modules/" \; 2>/dev/null || true
 
-              cd "${{ env.ANYKERNEL }}"
-              zip -r AnyKernel.zip *
-              mv -- "AnyKernel.zip" "${{ env.ZIP_NAME }}"
-              mv -- "${{ env.ANYKERNEL }}/${{ env.ZIP_NAME }}" "${{ env.OUTPUT_DIR }}/${{ env.ZIP_NAME }}"
-              rm -rf "${{ env.ANYKERNEL }}"
-         else
-              echo "ERROR: Kernel Image not found in arch/arm64/boot/!"
-              exit 1
-         fi
-         
-         zip_file=$(find ${{ env.OUTPUT_DIR }} -name '${{ github.event.inputs.KERNEL_NAME }}*.zip' -print -quit)
-         echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV
-         echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
+               cd "${{ env.ANYKERNEL }}"
+               zip -r AnyKernel.zip *
+               mv -- "AnyKernel.zip" "${{ env.ZIP_NAME }}"
+               mv -- "${{ env.ANYKERNEL }}/${{ env.ZIP_NAME }}" "${{ env.OUTPUT_DIR }}/${{ env.ZIP_NAME }}"
+               rm -rf "${{ env.ANYKERNEL }}"
+          else
+               echo "ERROR: Kernel Image not found in arch/arm64/boot/!"
+               exit 1
+          fi
+          
+          zip_file=$(find ${{ env.OUTPUT_DIR }} -name '${{ github.event.inputs.KERNEL_NAME }}*.zip' -print -quit)
+          echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV
+          echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
 
       - name: Upload files to repository releases page
         uses: softprops/action-gh-release@v1
